### ISSUE TITLE
Project Delay

### ISSUE THREAD

**Issue by ghost** [rstropek-teaching/real-time-game-quiz-4bhif-micky8186#1]
There have been problems with the time for the project. I'm probably not able to finish on time (11.January 2018). Nevertheless, development will continue.

**Comment by rstropek** [comment]
No problem. Finishing the project isn't the primary goal. The main goal of the project is that you practice working with Node.js, TypeScript, Web APIs, Websockets, etc. Don't worry if you cannot finish everything you planned. If you have spent some time practicing and gained more insights into the technologies mentioned before, you have reached the project's goal.

Greetings,
Rainer Stropek.
